CREATE DATABASE autocaelum;
USE autocaelum;

CREATE TABLE IF NOT EXISTS marcas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    marca VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    login VARCHAR(60) NOT NULL,
    senha VARCHAR(100) NOT NULL,
    ativo BOOLEAN DEFAULT 1
);

CREATE TABLE IF NOT EXISTS veiculos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    marca_id INT,
    FOREIGN KEY (marca_id) REFERENCES marcas (id)
    ON UPDATE CASCADE ON DELETE SET NULL,
    modelo VARCHAR(150) NOT NULL,
    preco DECIMAL(10, 2) NOT NULL DEFAULT 0,
    foto VARCHAR(150),
    descricao TEXT NOT NULL
);